//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShopII.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prikol
    {
        public Nullable<System.DateTime> DateUse { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Sum { get; set; }
        public int Id { get; set; }
    }
}
